defaults:
  - default
  - encoder: pixio
  - info_sharing: aat_ifr_24_layers
  - pred_head: dpt_pose_scale
  - task: images_only

# String for model factory
model_str: "pixio"
# Model config
model_config:
  name: "pixio"
  encoder_config: ${model.encoder}
  info_sharing_config: ${model.info_sharing}
  pred_head_config: ${model.pred_head}
  geometric_input_config: ${model.task}
# Image Normalization Type
data_norm_type: "dinov2"
