defaults:
  - default

# Root directory containing all datasets
root_data_dir: "/ocean/projects/cis220039p/shared/datasets"
# Dataset metadata directory
morphcloud_dataset_metadata_dir: "/ocean/projects/cis220039p/shared/morphcloud_dataset_metadata"
# Root directory containing pretrained checkpoints for custom models
root_pretrained_checkpoints_dir: "/jet/home/yzhang25/morphcloud/checkpoints"
# Root directory to log experiments
root_experiments_dir: "/jet/home/yzhang25/morphcloud/outputs"
# Root directory containing UniCeption pretrained checkpoints
root_uniception_pretrained_checkpoints_dir: "/ocean/projects/cis220039p/shared/uniception/checkpoints/"
# Root directory containing external benchmark data
external_benchmark_data_root_data_dir: "/jet/home/yzhang25/morphcloud/benchmarking/rmvd_mvs_benchmark/rmvd_test_data"
